[project]
name = "capstone"
version = "1.0.0"
requires-python = ">=3.11"
dependencies = [
    "dotenv==0.9.9",
    "faiss-cpu==1.10.0",
    "flask==3.1.0",
    "langchain==0.3.24",
    "langchain-community==0.3.22",
    "langchain-openai==0.3.14",
    "langchain-text-splitters==0.3.8",
]
